name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t skakarla9/liatrio-app .

    - name: Run the app in Docker
      run: docker run -d -p 80:80 --network host skakarla9/liatrio-app
    
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone Test Cases Repository
      run: git clone https://github.com/liatrio/github-actions.git

    - name: Install dependencies for the tests
      run: |
        cd github-actions/apprentice-action
        npm install

    - name: Run Mocha tests
      run: |
        cd github-actions/apprentice-action
        node index.js 

    - name: Output test results
      run: |
        cd github-actions/apprentice-action
        cat *.log


