name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image for Google Container Registry (GCR)
      run: docker build -t us-west2-docker.pkg.dev/liatrio-app/sliatrio:latest .

    - name: Run the app in Docker
      run: docker run -d -p 80:80 --network host us-west2-docker.pkg.dev/liatrio-app/sliatrio:latest 

    - name: Run Liatrio Apprentice Action
      uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: liatrio-app
        install_components: 'kubectl'
    
    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

    - name: Push Docker image to Google Container Registry
      run:  docker push us-west2-docker.pkg.dev/liatrio-app/sliatrio:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy liatrio-app \
          --image us-west2-docker.pkg.dev/liatrio-app/sliatrio:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated