name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t skakarla9/liatrio-app .

    - name: Run the Docker container
      run: docker run -d -p 80:80 --network host skakarla9/liatrio-app

    - name: Run only the first 6 test cases
      run: |
        echo "Running the first 6 test cases..."        
        npx playwright test --max-failures=6

    # Optional: Log in to Docker Hub if necessary for further steps
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Optional: Push Docker image to Docker Hub if necessary
    - name: Push Docker image to Docker Hub
      run: docker push skakarla9/liatrio-app:latest
